'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KMLkpwn.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to linksys
        '''&lt;no ssid&gt;
        '''default
        '''NETGEAR
        '''Wireless
        '''WLAN
        '''Belkin54g
        '''MSHOME
        '''home
        '''hpsetup
        '''smc
        '''tsunami
        '''ACTIONTEC
        '''orange
        '''USR8054
        '''101
        '''tmobile
        '''&lt;hidden ssid&gt;
        '''SpeedStream
        '''linksys-g
        '''3Com
        '''WaveLAN Network
        '''Wayport_Access
        '''hhonors
        '''pi07490509x
        '''pi07490509x09
        '''Motorola
        '''SST-PR-1
        '''ANY
        '''eurospot
        '''188ALT
        '''Gateway
        '''HomeNet
        '''GoldenTree
        '''SITECOM
        '''ConnectionPoint
        '''&lt;No current ssid&gt;
        '''Philips WiFi
        '''Customer ID
        '''PCX5000
        '''arescom
        '''Wireless Network
        '''Office
        '''Blitzz
        '''Airport
        '''INTERMEC
        '''freedomlink
        '''MSFTWLAN
        '''MIT
        '''Untitled
        '''GlobalSuiteWireless
        '''Cox-Hospitality
        '''NESPOT
        '''DLINK
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SSID() As String
            Get
                Return ResourceManager.GetString("SSID", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property the_planet_earth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("the_planet_earth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
